<?php

namespace Database\Factories;

use App\Models\Company;
use App\Models\Currency;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Customer>
 */
class CustomerFactory extends Factory
{
    protected $model = Customer::class;

    public function definition(): array
    {
        $company = Company::inRandomOrder()->first() ?? Company::factory()->create();
        $currency = Currency::where('code', 'USD')->first() ?? Currency::factory()->create(['code' => 'USD']);

        return [
            'id' => fake()->uuid(),
            'company_id' => $company->id,
            'customer_number' => null, // Will be generated by the model
            'name' => fake()->company(),
            'email' => fake()->optional(0.8)->companyEmail(),
            'phone' => fake()->optional(0.7)->phoneNumber(),
            'tax_id' => fake()->optional(0.4)->numerify('##########'),
            'currency_id' => $currency->id,
            'credit_limit' => fake()->randomFloat(2, 0, 50000),
            'payment_terms' => fake()->randomElement([15, 30, 45, 60, 90]),
            'billing_address' => [
                'street' => fake()->streetAddress(),
                'city' => fake()->city(),
                'state' => fake()->state(),
                'zip_code' => fake()->postcode(),
                'country' => fake()->country(),
            ],
            'shipping_address' => [
                'street' => fake()->streetAddress(),
                'city' => fake()->city(),
                'state' => fake()->state(),
                'zip_code' => fake()->postcode(),
                'country' => fake()->country(),
            ],
            'notes' => fake()->optional()->paragraph(),
            'is_active' => true,
            'metadata' => [
                'customer_type' => fake()->randomElement(['business', 'individual', 'government']),
                'industry' => fake()->randomElement(['technology', 'manufacturing', 'retail', 'services', 'healthcare']),
                'source' => fake()->randomElement(['website', 'referral', 'cold_call', 'trade_show', 'advertisement']),
                'lead_score' => fake()->numberBetween(1, 100),
            ],
        ];
    }

    public function business(): static
    {
        return $this->state(fn (array $attributes) => [
            'name' => fake()->company(),
            'email' => fake()->companyEmail(),
            'metadata' => array_merge($attributes['metadata'] ?? [], ['customer_type' => 'business']),
        ]);
    }

    public function individual(): static
    {
        return $this->state(fn (array $attributes) => [
            'name' => fake()->name(),
            'email' => fake()->email(),
            'metadata' => array_merge($attributes['metadata'] ?? [], ['customer_type' => 'individual']),
        ]);
    }

    public function government(): static
    {
        return $this->state(fn (array $attributes) => [
            'name' => fake()->company().' Government Agency',
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'customer_type' => 'government',
                'government_level' => fake()->randomElement(['federal', 'state', 'local']),
            ]),
        ]);
    }

    public function withHighCreditLimit(): static
    {
        return $this->state(fn (array $attributes) => [
            'credit_limit' => fake()->randomFloat(2, 50000, 500000),
        ]);
    }

    public function withLowCreditLimit(): static
    {
        return $this->state(fn (array $attributes) => [
            'credit_limit' => fake()->randomFloat(2, 0, 5000),
        ]);
    }

    public function noCreditLimit(): static
    {
        return $this->state(fn (array $attributes) => [
            'credit_limit' => 0,
        ]);
    }

    public function withStrictTerms(): static
    {
        return $this->state(fn (array $attributes) => [
            'payment_terms' => fake()->randomElement([0, 7, 15]),
            'credit_limit' => fake()->randomFloat(2, 0, 10000),
        ]);
    }

    public function withFlexibleTerms(): static
    {
        return $this->state(fn (array $attributes) => [
            'payment_terms' => fake()->randomElement([60, 90, 120]),
            'credit_limit' => fake()->randomFloat(2, 25000, 100000),
        ]);
    }

    public function active(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_active' => true,
        ]);
    }

    public function inactive(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_active' => false,
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'inactivation_reason' => fake()->randomElement([
                    'no_longer_customer',
                    'account_closed',
                    'fraud',
                    'bankruptcy',
                ]),
                'inactivation_date' => now()->subDays(fake()->numberBetween(1, 365))->toISOString(),
            ]),
        ]);
    }

    public function forCompany(Company $company): static
    {
        return $this->state(fn (array $attributes) => [
            'company_id' => $company->id,
        ]);
    }

    public function withContacts(int $count = 1): static
    {
        return $this->afterCreating(function ($customer) use ($count) {
            Contact::factory()->count($count)->create([
                'customer_id' => $customer->id,
                'company_id' => $customer->company_id,
            ]);
        });
    }

    public function withInvoices(int $count = 1): static
    {
        return $this->afterCreating(function ($customer) use ($count) {
            Invoice::factory()->count($count)->create([
                'company_id' => $customer->company_id,
                'customer_id' => $customer->id,
            ]);
        });
    }

    public function withPayments(int $count = 1): static
    {
        return $this->afterCreating(function ($customer) use ($count) {
            Payment::factory()->count($count)->create([
                'company_id' => $customer->company_id,
                'customer_id' => $customer->id,
            ]);
        });
    }

    public function technology(): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'industry' => 'technology',
                'sub_industry' => fake()->randomElement(['software', 'hardware', 'saas', 'consulting']),
            ]),
        ]);
    }

    public function manufacturing(): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'industry' => 'manufacturing',
                'sub_industry' => fake()->randomElement(['automotive', 'electronics', 'textiles', 'food']),
            ]),
        ]);
    }

    public function retail(): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'industry' => 'retail',
                'sub_industry' => fake()->randomElement(['clothing', 'electronics', 'grocery', 'department_store']),
            ]),
        ]);
    }

    public function services(): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'industry' => 'services',
                'sub_industry' => fake()->randomElement(['consulting', 'legal', 'accounting', 'marketing']),
            ]),
        ]);
    }

    public function healthcare(): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'industry' => 'healthcare',
                'sub_industry' => fake()->randomElement(['hospital', 'clinic', 'pharmaceutical', 'medical_device']),
            ]),
        ]);
    }

    public function withNotes(string $notes): static
    {
        return $this->state(fn (array $attributes) => [
            'notes' => $notes,
        ]);
    }

    public function withTaxId(string $taxId): static
    {
        return $this->state(fn (array $attributes) => [
            'tax_id' => $taxId,
        ]);
    }

    public function withPhone(string $phone): static
    {
        return $this->state(fn (array $attributes) => [
            'phone' => $phone,
        ]);
    }

    public function withEmail(string $email): static
    {
        return $this->state(fn (array $attributes) => [
            'email' => $email,
        ]);
    }
}
