<?php

namespace Database\Factories;

use App\Models\Company;
use App\Models\Currency;
use App\Models\Customer;
use App\Models\Invoice;
use App\Models\InvoiceItem;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Invoice>
 */
class InvoiceFactory extends Factory
{
    protected $model = Invoice::class;

    public function definition(): array
    {
        $company = Company::inRandomOrder()->first() ?? Company::factory()->create();
        $customer = Customer::factory()->create(['company_id' => $company->id]);
        $currency = Currency::where('code', 'USD')->first() ?? Currency::factory()->create(['code' => 'USD']);

        $invoiceDate = fake()->dateTimeBetween('-6 months', 'now');
        $dueDate = fake()->dateTimeBetween($invoiceDate, '+60 days');

        $statuses = ['draft', 'sent', 'posted', 'partial', 'paid'];
        $status = fake()->randomElement($statuses);

        $subtotal = fake()->randomFloat(2, 100, 10000);
        $taxRate = fake()->randomFloat(2, 0, 20);
        $totalTax = $subtotal * ($taxRate / 100);
        $totalAmount = $subtotal + $totalTax;

        $paidAmount = match ($status) {
            'paid' => $totalAmount,
            'partial' => fake()->randomFloat(2, 0, $totalAmount * 0.9),
            default => 0,
        };

        $balanceDue = $totalAmount - $paidAmount;

        return [
            'company_id' => $company->id,
            'customer_id' => $customer->id,
            'currency_id' => $currency->id,
            'invoice_number' => null, // Will be generated by the model
            'invoice_date' => $invoiceDate,
            'due_date' => $dueDate,
            'subtotal' => $subtotal,
            'tax_amount' => $totalTax,
            'total_amount' => $totalAmount,
            'paid_amount' => $paidAmount,
            'balance_due' => $balanceDue,
            'status' => $status,
            'notes' => fake()->optional()->sentence(),
            'terms' => fake()->optional()->paragraph(),
            'metadata' => [
                'created_by' => 'factory',
                'source' => 'test',
            ],
        ];
    }

    public function draft(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'draft',
            'paid_amount' => 0,
            'balance_due' => $attributes['total_amount'],
        ]);
    }

    public function sent(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'sent',
            'paid_amount' => 0,
            'balance_due' => $attributes['total_amount'],
            'sent_at' => now(),
        ]);
    }

    public function posted(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'posted',
            'paid_amount' => 0,
            'balance_due' => $attributes['total_amount'],
            'sent_at' => now()->subDays(1),
            'posted_at' => now(),
        ]);
    }

    public function paid(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'paid',
            'paid_amount' => $attributes['total_amount'],
            'balance_due' => 0,
            'sent_at' => now()->subDays(5),
            'posted_at' => now()->subDays(4),
        ]);
    }

    public function partial(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'partial',
            'paid_amount' => fake()->randomFloat(2, 1, $attributes['total_amount'] * 0.9),
            'balance_due' => fn ($attributes) => $attributes['total_amount'] - $attributes['paid_amount'],
        ]);
    }

    public function overdue(): static
    {
        return $this->state(fn (array $attributes) => [
            'due_date' => fake()->dateTimeBetween('-60 days', '-1 day'),
            'status' => fake()->randomElement(['sent', 'posted', 'partial']),
            'paid_amount' => fake()->randomFloat(2, 0, $attributes['total_amount'] * 0.5),
            'balance_due' => fn ($attributes) => $attributes['total_amount'] - $attributes['paid_amount'],
        ]);
    }

    public function highValue(): static
    {
        return $this->state(function (array $attributes) {
            $subtotal = fake()->randomFloat(2, 5000, 50000);
            $taxAmount = $attributes['tax_amount'] ?? 0;

            return [
                'subtotal' => $subtotal,
                'total_amount' => $subtotal + $taxAmount,
            ];
        });
    }

    public function lowValue(): static
    {
        return $this->state(function (array $attributes) {
            $subtotal = fake()->randomFloat(2, 10, 500);
            $taxAmount = $attributes['tax_amount'] ?? 0;

            return [
                'subtotal' => $subtotal,
                'total_amount' => $subtotal + $taxAmount,
            ];
        });
    }

    public function withTax(float $taxRate = 15.0): static
    {
        return $this->state(function (array $attributes) use ($taxRate) {
            $subtotal = $attributes['subtotal'] ?? fake()->randomFloat(2, 100, 10000);
            $taxAmount = $subtotal * ($taxRate / 100);

            return [
                'tax_amount' => $taxAmount,
                'total_amount' => $subtotal + $taxAmount,
            ];
        });
    }

    public function withItems(int $count = 3): static
    {
        return $this->afterCreating(function (Invoice $invoice) use ($count) {
            InvoiceItem::factory()->count($count)->create([
                'invoice_id' => $invoice->getKey(),
            ]);

            $invoice->calculateTotals();
            $invoice->save();
        });
    }

    public function forCompany(Company $company): static
    {
        return $this->state(fn (array $attributes) => [
            'company_id' => $company->id,
            'customer_id' => Customer::factory()->create(['company_id' => $company->id])->id,
        ]);
    }

    public function forCustomer(Customer $customer): static
    {
        return $this->state(fn (array $attributes) => [
            'company_id' => $customer->company_id,
            'customer_id' => $customer->id,
        ]);
    }
}
