<?php

namespace Database\Factories;

use App\Models\Company;
use App\Models\Currency;
use App\Models\ItemCategory;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Item>
 */
class ItemFactory extends Factory
{
    protected $model = \App\Models\Item::class;

    public function definition(): array
    {
        $company = Company::inRandomOrder()->first() ?? Company::factory()->create();
        $currency = Currency::where('code', 'USD')->first() ?? Currency::factory()->create(['code' => 'USD']);
        $category = ItemCategory::inRandomOrder()->first() ?? ItemCategory::factory()->create(['company_id' => $company->id]);

        return [
            'id' => fake()->uuid(),
            'company_id' => $company->id,
            'item_code' => null, // Will be generated by the model
            'name' => fake()->words(3, true),
            'description' => fake()->optional()->paragraph(),
            'unit_price' => fake()->randomFloat(2, 10, 1000),
            'currency_id' => $currency->id,
            'item_type' => fake()->randomElement(['service', 'product']),
            'category_id' => $category->id,
            'taxable' => fake()->boolean(80),
            'track_inventory' => fake()->boolean(60),
            'reorder_level' => fake()->randomFloat(2, 0, 100),
            'stock_quantity' => fake()->randomFloat(2, 0, 1000),
            'is_active' => true,
            'metadata' => [
                'created_by' => 'factory',
                'item_class' => fake()->randomElement(['standard', 'premium', 'budget']),
                'supplier' => fake()->optional()->company(),
                'brand' => fake()->optional()->word(),
            ],
        ];
    }

    public function service(): static
    {
        return $this->state(fn (array $attributes) => [
            'item_type' => 'service',
            'track_inventory' => false,
            'stock_quantity' => 0,
            'reorder_level' => 0,
            'metadata' => array_merge($attributes['metadata'] ?? [], ['service_type' => 'professional']),
        ]);
    }

    public function product(): static
    {
        return $this->state(fn (array $attributes) => [
            'item_type' => 'product',
            'track_inventory' => true,
            'stock_quantity' => fake()->randomFloat(2, 10, 1000),
            'reorder_level' => fake()->randomFloat(2, 5, 50),
            'metadata' => array_merge($attributes['metadata'] ?? [], ['product_type' => 'physical']),
        ]);
    }

    public function software(): static
    {
        return $this->state(fn (array $attributes) => [
            'name' => fake()->randomElement([
                'Software License',
                'SaaS Subscription',
                'Software Development',
                'Technical Support',
                'Cloud Services',
                'API Access',
                'Database Services',
                'Security Software',
            ]),
            'item_type' => 'service',
            'track_inventory' => false,
            'unit_price' => fake()->randomFloat(2, 50, 5000),
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'software_type' => fake()->randomElement(['license', 'subscription', 'development', 'support']),
                'license_type' => fake()->randomElement(['perpetual', 'annual', 'monthly']),
            ]),
        ]);
    }

    public function hardware(): static
    {
        return $this->state(fn (array $attributes) => [
            'name' => fake()->randomElement([
                'Laptop Computer',
                'Desktop Computer',
                'Server Hardware',
                'Networking Equipment',
                'Storage Device',
                'Monitor',
                'Keyboard',
                'Mouse',
                'Printer',
            ]),
            'item_type' => 'product',
            'track_inventory' => true,
            'unit_price' => fake()->randomFloat(2, 100, 5000),
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'hardware_type' => fake()->randomElement(['computer', 'peripheral', 'networking', 'storage']),
                'warranty_period' => fake()->randomElement(['1 year', '2 years', '3 years', '5 years']),
            ]),
        ]);
    }

    public function consulting(): static
    {
        return $this->state(fn (array $attributes) => [
            'name' => fake()->randomElement([
                'Business Consulting',
                'Technical Consulting',
                'Strategic Planning',
                'Process Improvement',
                'Risk Assessment',
                'Compliance Review',
                'Project Management',
                'Change Management',
            ]),
            'item_type' => 'service',
            'track_inventory' => false,
            'unit_price' => fake()->randomFloat(2, 100, 1000),
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'consulting_type' => fake()->randomElement(['business', 'technical', 'strategic', 'financial']),
                'hourly_rate' => $attributes['unit_price'],
            ]),
        ]);
    }

    public function officeSupplies(): static
    {
        return $this->state(fn (array $attributes) => [
            'name' => fake()->randomElement([
                'Paper',
                'Pens',
                'Notebooks',
                'Folders',
                'Staples',
                'Paper Clips',
                'Envelopes',
                'Markers',
                'Tape',
            ]),
            'item_type' => 'product',
            'track_inventory' => true,
            'unit_price' => fake()->randomFloat(2, 1, 50),
            'metadata' => array_merge($attributes['metadata'] ?? [], ['category' => 'office_supplies']),
        ]);
    }

    public function highValue(): static
    {
        return $this->state(fn (array $attributes) => [
            'unit_price' => fake()->randomFloat(2, 1000, 50000),
        ]);
    }

    public function lowValue(): static
    {
        return $this->state(fn (array $attributes) => [
            'unit_price' => fake()->randomFloat(2, 1, 100),
        ]);
    }

    public function taxable(): static
    {
        return $this->state(fn (array $attributes) => [
            'taxable' => true,
        ]);
    }

    public function taxExempt(): static
    {
        return $this->state(fn (array $attributes) => [
            'taxable' => false,
            'metadata' => array_merge($attributes['metadata'] ?? [], ['tax_exemption_reason' => 'educational']),
        ]);
    }

    public function trackInventory(): static
    {
        return $this->state(fn (array $attributes) => [
            'track_inventory' => true,
            'stock_quantity' => fake()->randomFloat(2, 10, 1000),
            'reorder_level' => fake()->randomFloat(2, 5, 50),
        ]);
    }

    public function noInventoryTracking(): static
    {
        return $this->state(fn (array $attributes) => [
            'track_inventory' => false,
            'stock_quantity' => 0,
            'reorder_level' => 0,
        ]);
    }

    public function inStock(): static
    {
        return $this->state(fn (array $attributes) => [
            'track_inventory' => true,
            'stock_quantity' => fake()->randomFloat(2, 50, 1000),
            'reorder_level' => fake()->randomFloat(2, 10, 100),
        ]);
    }

    public function lowStock(): static
    {
        return $this->state(fn (array $attributes) => [
            'track_inventory' => true,
            'stock_quantity' => fake()->randomFloat(2, 0, 10),
            'reorder_level' => fake()->randomFloat(2, 5, 20),
        ]);
    }

    public function outOfStock(): static
    {
        return $this->state(fn (array $attributes) => [
            'track_inventory' => true,
            'stock_quantity' => 0,
            'reorder_level' => fake()->randomFloat(2, 5, 20),
            'metadata' => array_merge($attributes['metadata'] ?? [], ['out_of_stock' => true]),
        ]);
    }

    public function active(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_active' => true,
        ]);
    }

    public function inactive(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_active' => false,
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'inactivation_reason' => fake()->randomElement(['discontinued', 'obsolete', 'replaced']),
            ]),
        ]);
    }

    public function forCompany(Company $company): static
    {
        return $this->state(fn (array $attributes) => [
            'company_id' => $company->id,
            'category_id' => ItemCategory::factory()->create(['company_id' => $company->id])->id,
        ]);
    }

    public function withCategory(ItemCategory $category): static
    {
        return $this->state(fn (array $attributes) => [
            'category_id' => $category->id,
            'company_id' => $category->company_id,
        ]);
    }

    public function withDescription(string $description): static
    {
        return $this->state(fn (array $attributes) => [
            'description' => $description,
        ]);
    }

    public function withSupplier(string $supplier): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => array_merge($attributes['metadata'] ?? [], ['supplier' => $supplier]),
        ]);
    }

    public function withBrand(string $brand): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => array_merge($attributes['metadata'] ?? [], ['brand' => $brand]),
        ]);
    }

    public function withSKU(string $sku): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => array_merge($attributes['metadata'] ?? [], ['sku' => $sku]),
        ]);
    }

    public function withBarcode(string $barcode): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => array_merge($attributes['metadata'] ?? [], ['barcode' => $barcode]),
        ]);
    }

    public function withWeight(float $weight): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => array_merge($attributes['metadata'] ?? [], ['weight' => $weight, 'weight_unit' => 'kg']),
        ]);
    }

    public function withDimensions(array $dimensions): static
    {
        return $this->state(fn (array $attributes) => [
            'metadata' => array_merge($attributes['metadata'] ?? [], [
                'dimensions' => $dimensions,
                'dimension_unit' => 'cm',
            ]),
        ]);
    }

    public function premium(): static
    {
        return $this->state(fn (array $attributes) => [
            'unit_price' => fake()->randomFloat(2, 500, 10000),
            'metadata' => array_merge($attributes['metadata'] ?? [], ['item_class' => 'premium']),
        ]);
    }

    public function standard(): static
    {
        return $this->state(fn (array $attributes) => [
            'unit_price' => fake()->randomFloat(2, 50, 500),
            'metadata' => array_merge($attributes['metadata'] ?? [], ['item_class' => 'standard']),
        ]);
    }

    public function budget(): static
    {
        return $this->state(fn (array $attributes) => [
            'unit_price' => fake()->randomFloat(2, 1, 50),
            'metadata' => array_merge($attributes['metadata'] ?? [], ['item_class' => 'budget']),
        ]);
    }
}
